### ISSUE TITLE
RUA or RUF?

### ISSUE THREAD

**Issue by fribse** [jertel/dmarc2logstash#11]
Hi @jertel 
Another question, I've set everything up with RUA, but will the script handle RUF as well and give more data?

**Comment by jertel** [comment]
No, the script only support DMARC RUA. Are you receiving many RUF reports? They are rare since many email systems don't send them due to privacy concerns.

**Comment by fribse** [comment]
No, I dont think so, and I've only given rua settings in the dmarc records,I was just wondering, thankyou for clearing it up.
