### ISSUE TITLE
POP3 error on office365

### ISSUE THREAD

**Issue by fribse** [jertel/dmarc2logstash#4]
I'm suddenly getting errors when it tries to log into office 365.
The account hasn't changed, and the logfile haven't changed.
At first I thought the password might have expired, so I changed it, but that didn't change anything.
I can connect with telnet or socar to 110/995 from the server it's running on.

Logging in with a POP3 client works (just tried with MAIL from M$) with the new username password.
This is what I see in the logfile
dmarc             | Traceback (most recent call last):
dmarc             |   File "/opt/dmarc2logstash/dmarc2logstash.py", line 203, in <module>
dmarc             |     sys.exit(main())
dmarc             |   File "/opt/dmarc2logstash/dmarc2logstash.py", line 200, in main
dmarc             |     start(server, username, password, int(sleepSec), jsonOutputFile, float(timeout), int(shouldDelete))
dmarc             |   File "/opt/dmarc2logstash/dmarc2logstash.py", line 163, in start
dmarc             |     download(server, username, password, jsonOutputFile, timeout, shouldDelete)
dmarc             |   File "/opt/dmarc2logstash/dmarc2logstash.py", line 41, in download
dmarc             |     conn = connect(server, username, password, timeout)
dmarc             |   File "/opt/dmarc2logstash/dmarc2logstash.py", line 35, in connect
dmarc             |     conn.pass_(password)
dmarc             |   File "/usr/lib/python2.7/poplib.py", line 197, in pass_
dmarc             |     return self._shortcmd('PASS %s' % pswd)
dmarc             |   File "/usr/lib/python2.7/poplib.py", line 160, in _shortcmd
dmarc             |     return self._getresp()
dmarc             |   File "/usr/lib/python2.7/poplib.py", line 136, in _getresp
dmarc             |     raise error_proto(resp)
dmarc             | poplib.error_proto: -ERR Logon failure: unknown user name or bad password.

**Comment by jertel** [comment]
Hello. Did you enable POP3 debugging to understand what's happening at the POP3 layer?

This is mentioned in the README.md:

![image](https://user-images.githubusercontent.com/16639611/60181051-5de86500-97ef-11e9-8f61-db0bd4f73ed4.png)
